Check that the driver is installed first

diff --git a/set-hp-defaults b/set-hp-defaults
--- a/set-hp-defaults
+++ b/set-hp-defaults
@@ -8,6 +8,13 @@
 
 set -e
 
+drivername="HP Color MFP E77822-25-30"
+lpinfo --make-and-model "$drivername" -m > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "Error: $drivername printer driver missing"
+  exit 1
+fi
+
 echo
 printf "\e[1mCUPS printer names:\e[0m\n"; lpstat -a | cut -f1 -d ' '; echo
 
